### ISSUE TITLE
No module named 'vtracer.vtracer'

### ISSUE THREAD

**Issue by suede299** [al-swaiti/ComfyUI-OllamaGemini#11]
Traceback (most recent call last):
  File "H:\StableSwarmUI\dlbackend\comfy\ComfyUI\nodes.py", line 2022, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "H:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-OllamaGemini\__init__.py", line 21, in <module>
    from .GeminiOllamaNode import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "H:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-OllamaGemini\GeminiOllamaNode.py", line 13, in <module>
    from .svgnode import ConvertRasterToVector, SaveSVG
  File "H:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-OllamaGemini\svgnode.py", line 1, in <module>
    import vtracer
  File "H:\StableSwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\vtracer\__init__.py", line 1, in <module>
    from .vtracer import (convert_image_to_svg_py, convert_pixels_to_svg,
ModuleNotFoundError: No module named 'vtracer.vtracer'

<img width="299" alt="{25B0F3E5-B752-4394-ACBE-0F4961D644EA}" src="https://github.com/user-attachments/assets/aeb7c00f-2e1c-47f0-91a6-1f9a68af61b6">

**Comment by al-swaiti** [comment]
Did you install the library
