### ISSUE TITLE
Import Failed: Charmap Issue

### ISSUE THREAD

**Issue by Mohsyn** [al-swaiti/ComfyUI-OllamaGemini#8]
I get following error and Import failed on launch:

Traceback (most recent call last):
  File "D:\comfyui\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\comfyui\ComfyUI\custom_nodes\ComfyUI-OllamaGemini\__init__.py", line 21, in <module>
    from .GeminiOllamaNode import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\comfyui\ComfyUI\custom_nodes\ComfyUI-OllamaGemini\GeminiOllamaNode.py", line 15, in <module>
    from .prompt_styler import *
  File "D:\comfyui\ComfyUI\custom_nodes\ComfyUI-OllamaGemini\prompt_styler.py", line 39, in <module>
    styler_data = StylerData()
  File "D:\comfyui\ComfyUI\custom_nodes\ComfyUI-OllamaGemini\prompt_styler.py", line 24, in __init__
    content = json.load(f)
  File "json\__init__.py", line 293, in load
  File "encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 133220: character maps to <undefined>

Cannot import D:\comfyui\ComfyUI\custom_nodes\ComfyUI-OllamaGemini module for custom nodes: 'charmap' codec can't decode byte 0x8d in position 133220: character maps to <undefined>

**Comment by HeavyTony2** [comment]
Same problem here
